name: build

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare env
        run: |
          apt update
          apt install -y build-essential make tree
      - name: Build package
        run: |
          cp -a src flaskapp/opt/flaskapp
          dpkg-deb -b flaskapp
          ls -alh
      - name: Test package
        run: |
          dpkg -i ./flaskapp.deb
          tree /opt
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: flaskapp.deb
          retention-days: 5


