name: build

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
      - name: Prepare env
	run: ls -al
        	
