name: Cypress Tests

on: [push]

jobs:
  chrome:
    runs-on: ubuntu-latest
#    container: cypress/browsers:node12.18.3-chrome87-ff82
#    needs: install
    strategy:
      fail-fast: false
      matrix:
        viewports: ["macbook-13", "ipad-mini", "iphone-xr", "samsung-note9"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          record: true
          parallel: true
          group: ${{ matrix.viewports }}
          config: "viewport=${{ matrix.viewports }}"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
