name: Cypress Tests

on: [push]


# ToDo: start app before deploy and run tests, after tests pass, than do deploy

jobs:
  chrome:
    runs-on: ubuntu-latest
#    container: cypress/browsers:node12.18.3-chrome87-ff82
#    needs: Deploy
    strategy:
      fail-fast: false
      matrix:
        viewports:
        - name: Desktopp
          width: 1920
          height: 1080
        - name: iPad-Pro-12
          width: 1024
          height: 1366
        - name: iPhone-x
          width: 375
          height: 812


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          record: true
          parallel: true
          group: ${{ matrix.name }}
          config: "viewportHeight=${{ matrix.height }},viewportWidth=${{ matrix.width }}"
        env:
          # pass the Dashboard record key as an environment variable
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_BASE_URL: https://flaskapp.fejk.net
