name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and publish image 
      run: |
        env
        export TIME=$(date +%F.%H.%M)
        export BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///g')
        # Build image 
        docker build --tag theztd/flaskapp:${BRANCH_NAME} .

        # Add tag with a build time
        docker image tag theztd/flaskapp:${BRANCH_NAME} theztd/flaskapp:${TIME}
      
        # Push both images to docker registry
        docker push theztd/flaskapp:${BRANCH_NAME}
        docker push theztd/flaskapp:${TIME}

