name: build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: theztd/nomad:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy application
        run: |
            nomad job run deploy.hcl
        env:
            NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
            NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
